-- Seed the Supabase-backed global medication library used by practice adoption.
-- The frontend can preview local fallback cards, but practice_medication_cards
-- has a foreign key to medications(code), so global adoption needs these rows.

INSERT INTO medications (
  code,
  title,
  description,
  badge,
  category,
  key_info,
  nhs_link,
  trend_links,
  sick_days_needed,
  review_months,
  is_deleted,
  updated_at
) VALUES
  (
    '101',
    $$Sulfonylurea medicine - Starting Treatment$$,
    $$Sulfonylureas such as gliclazide and glimepiride help your body make more insulin to lower your blood sugar.$$,
    'NEW',
    $$Sulfonylureas$$,
    ARRAY[$$Take this medication with a meal.$$, $$Be aware of "hypos" (low blood sugar).$$, $$Always carry glucose or a sugary snack.$$],
    $$https://www.nhs.uk/medicines/gliclazide/$$,
    '[{"title":"Hypoglycaemia Explained","url":"https://trenddiabetes.online/wp-content/uploads/2026/01/A5_Hypo_TREND.pdf"}]'::jsonb,
    false,
    12,
    false,
    now()
  ),
  (
    '102',
    $$Sulfonylurea medicine - Reauthorisation$$,
    $$Sulfonylureas such as gliclazide and glimepiride remain an important part of blood sugar treatment by helping your body make more insulin.$$,
    'REAUTH',
    $$Sulfonylureas$$,
    ARRAY[$$Continue taking as prescribed, usually with breakfast.$$, $$Maintain regular check-ups.$$],
    $$https://www.nhs.uk/medicines/gliclazide/$$,
    '[{"title":"Keeping well with T2 Diabetes","url":"https://trenddiabetes.online/wp-content/uploads/2023/10/A5_Older_Person_TREND.pdf"}]'::jsonb,
    false,
    12,
    false,
    now()
  ),
  (
    '201',
    $$SGLT2 inhibitor medicine - Starting Treatment$$,
    $$SGLT2 inhibitors such as dapagliflozin and empagliflozin, which often end in "-gliflozin", help your body pass extra sugar in your urine.$$,
    'NEW',
    $$SGLT2 Inhibitors$$,
    ARRAY[$$Stay hydrated by drinking plenty of water.$$, $$Maintain good personal hygiene to reduce infection risk.$$, $$Be aware of the risk of Ketoacidosis (rare but serious).$$],
    $$https://www.nhs.uk/conditions/type-2-diabetes/medicine/$$,
    '[{"title":"A simple guide to SGLT2 inhibitors","url":"https://trenddiabetes.online/wp-content/uploads/2025/10/SGLT2i_TREND_FINAL_v2.pdf"},{"title":"Genital Fungal Infection Prevention","url":"https://trenddiabetes.online/wp-content/uploads/2025/07/A5_Genital_TREND.pdf"}]'::jsonb,
    true,
    12,
    false,
    now()
  ),
  (
    '202',
    $$SGLT2 inhibitor medicine - Reauthorisation$$,
    $$SGLT2 inhibitors such as dapagliflozin and empagliflozin, which often end in "-gliflozin", can help lower blood sugar and may also protect your heart and kidneys.$$,
    'REAUTH',
    $$SGLT2 Inhibitors$$,
    ARRAY[$$Continue to stay hydrated.$$, $$Remember "Sick Day Rules" (Pause medication if you are unable to eat or drink).$$],
    $$https://www.nhs.uk/conditions/type-2-diabetes/medicine/$$,
    '[{"title":"A simple guide to SGLT2 inhibitors","url":"https://trenddiabetes.online/wp-content/uploads/2025/10/SGLT2i_TREND_FINAL_v2.pdf"},{"title":"Sick Day Rules","url":"https://trenddiabetes.online/wp-content/uploads/2025/08/A5_T2Illness_TREND.pdf"}]'::jsonb,
    true,
    12,
    false,
    now()
  ),
  (
    '301',
    $$Emollient and skin care treatment - Starting Treatment$$,
    $$Emollients such as Cetraben, Diprobase and E45 moisturise your skin and help soothe dryness and irritation.$$,
    'NEW',
    $$Dermatology$$,
    ARRAY[$$Apply frequently and in the direction of hair growth.$$, $$Important: Emollients with paraffin or oils are flammable. Keep away from naked flames.$$, $$Wash your hands after application if smoking.$$],
    $$https://www.nhs.uk/conditions/emollients/$$,
    '[]'::jsonb,
    false,
    12,
    false,
    now()
  ),
  (
    '302',
    $$Emollient and skin care treatment - Reauthorisation$$,
    $$Emollients such as Cetraben, Diprobase and E45 help protect the skin barrier and soothe dryness when used regularly.$$,
    'REAUTH',
    $$Dermatology$$,
    ARRAY[$$Continue applying regularly and in the direction of hair growth.$$, $$Important: Emollients with paraffin or oils are flammable. Keep away from naked flames.$$, $$Re-order before you run out so your skin care routine stays consistent.$$],
    $$https://www.nhs.uk/conditions/emollients/$$,
    '[]'::jsonb,
    false,
    12,
    false,
    now()
  ),
  (
    '401',
    $$Insulin therapy - Starting Treatment$$,
    $$Insulin treatments such as Levemir, Tresiba and Humulin help control your blood sugar and need careful day-to-day use.$$,
    'NEW',
    $$Insulin$$,
    ARRAY[$$Rotate your injection sites regularly.$$, $$Check your injection sites for lumps (Lipohypertrophy).$$, $$Inform the DVLA if you are a driver on insulin.$$],
    $$https://www.nhs.uk/conditions/type-1-diabetes/insulin/$$,
    '[{"title":"Keeping safe with insulin therapy","url":"https://trenddiabetes.online/wp-content/uploads/2025/08/A5_Insulin_TREND.pdf"},{"title":"Using an insulin cartridge pen","url":"https://trenddiabetes.online/wp-content/uploads/2023/08/A4_Novopen_Factsheet_TREND_v6-2.pdf"}]'::jsonb,
    true,
    12,
    false,
    now()
  ),
  (
    '402',
    $$Insulin therapy - Reauthorisation$$,
    $$Insulin treatments such as Levemir, Tresiba and Humulin remain an important part of blood sugar management and should be used in line with your insulin plan.$$,
    'REAUTH',
    $$Insulin$$,
    ARRAY[$$Continue rotating your injection sites regularly.$$, $$Check your injection sites for lumps (Lipohypertrophy).$$, $$Inform the DVLA if you are a driver on insulin.$$],
    $$https://www.nhs.uk/conditions/type-1-diabetes/insulin/$$,
    '[{"title":"Keeping safe with insulin therapy","url":"https://trenddiabetes.online/wp-content/uploads/2025/08/A5_Insulin_TREND.pdf"},{"title":"Using an insulin cartridge pen","url":"https://trenddiabetes.online/wp-content/uploads/2023/08/A4_Novopen_Factsheet_TREND_v6-2.pdf"}]'::jsonb,
    true,
    12,
    false,
    now()
  ),
  (
    '501',
    $$Mounjaro (Tirzepatide) - Starting Treatment$$,
    $$Mounjaro, also called tirzepatide, helps improve blood sugar control in type 2 diabetes and may also help with weight management.$$,
    'NEW',
    $$GLP-1 / GIP$$,
    ARRAY[$$Usually a once-weekly injection.$$, $$May cause nausea or gastrointestinal side effects initially.$$, $$Report any severe abdominal pain immediately.$$],
    $$https://www.nhs.uk/medicines/tirzepatide-mounjaro/$$,
    '[{"title":"GLP-1 RA and GIP guide","url":"https://trenddiabetes.online/wp-content/uploads/2025/11/GLP1RA_TREND_FINAL.pdf"}]'::jsonb,
    false,
    12,
    false,
    now()
  ),
  (
    '502',
    $$Mounjaro (Tirzepatide) - Reauthorisation$$,
    $$Mounjaro, also called tirzepatide, supports blood sugar control in type 2 diabetes and should be monitored for side effects or dose changes.$$,
    'REAUTH',
    $$GLP-1 / GIP$$,
    ARRAY[$$Usually a once-weekly injection.$$, $$May cause nausea or gastrointestinal side effects initially.$$, $$Report any severe abdominal pain immediately.$$],
    $$https://www.nhs.uk/medicines/tirzepatide-mounjaro/$$,
    '[{"title":"GLP-1 RA and GIP guide","url":"https://trenddiabetes.online/wp-content/uploads/2025/11/GLP1RA_TREND_FINAL.pdf"}]'::jsonb,
    false,
    12,
    false,
    now()
  )
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  badge = EXCLUDED.badge,
  category = EXCLUDED.category,
  key_info = EXCLUDED.key_info,
  nhs_link = EXCLUDED.nhs_link,
  trend_links = EXCLUDED.trend_links,
  sick_days_needed = EXCLUDED.sick_days_needed,
  review_months = EXCLUDED.review_months,
  is_deleted = false,
  deleted_at = null,
  deleted_by = null,
  updated_at = now();
